/**
 * Inlines src/data/docs/*.md into a generated TS module.
 *
 * DECISION #14: the markdown files are the source of truth, but reading them
 * with fs at request time is unreliable on Vercel — files under src/ are not
 * guaranteed to be traced into the serverless bundle. Generating a module at
 * build time keeps one copy authored by hand and removes the runtime file
 * dependency entirely.
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = join(here, "..", "src", "data", "docs");
const outFile = join(here, "..", "src", "data", "corpus.generated.ts");

const CLASSES: Record<string, { title: string; cls: string; blurb: string }> = {
  runbook: {
    title: "Payments Production Runbook",
    cls: "Operational Runbook",
    blurb: "Deploy, rollback, and incident response for a payments service.",
  },
  techdoc: {
    title: "Ledger API Documentation",
    cls: "Technical Documentation",
    blurb: "Auth, idempotency, pagination, rate limits, and error semantics.",
  },
  plan: {
    title: "Search Re-Platform Plan",
    cls: "Execution Plan",
    blurb: "Four-phase migration plan with dependencies and risks.",
  },
  skillfile: {
    title: "Skill: Repository Triage",
    cls: "Skill File",
    blurb: "How an agent should orient itself in an unfamiliar repository.",
  },
  kb: {
    title: "Platform Engineering KB",
    cls: "Knowledge Base",
    blurb: "Repeatedly-asked internal platform questions.",
  },
  handbook: {
    title: "Engineering Handbook",
    cls: "Knowledge Base (large)",
    blurb:
      "A long reference document. Included to test how token reduction scales with document size.",
  },
};

const files = readdirSync(docsDir).filter((f) => f.endsWith(".md"));

const entries = files.map((f) => {
  const id = f.replace(/\.md$/, "");
  const raw = readFileSync(join(docsDir, f), "utf8");
  const meta = CLASSES[id] ?? { title: id, cls: "Document", blurb: "" };
  return { id, raw, ...meta };
});

const body = `// AUTO-GENERATED by scripts/build-corpus.ts — do not edit.
// Source of truth: src/data/docs/*.md

export interface CorpusDoc {
  id: string;
  title: string;
  cls: string;
  blurb: string;
  markdown: string;
}

export const CORPUS: CorpusDoc[] = ${JSON.stringify(
  entries.map((e) => ({
    id: e.id,
    title: e.title,
    cls: e.cls,
    blurb: e.blurb,
    markdown: e.raw,
  })),
  null,
  2
)};

export function getDoc(id: string): CorpusDoc | undefined {
  return CORPUS.find((d) => d.id === id);
}
`;

writeFileSync(outFile, body, "utf8");
console.log(`corpus: ${entries.length} documents -> src/data/corpus.generated.ts`);

/* ---- code sample for the code-bridge page ---------------------------- */
// Uses this project's own source, so the demo is a real file rather than a toy.
const codeFiles = [
  { path: "src/lib/og/primitives.ts", label: "primitives.ts" },
  { path: "src/lib/og/transpiler.ts", label: "transpiler.ts" },
];

const codeOut = join(here, "..", "src", "data", "codesample.generated.ts");
const samples = codeFiles.map((f) => ({
  ...f,
  source: readFileSync(join(here, "..", f.path), "utf8"),
}));

writeFileSync(
  codeOut,
  `// AUTO-GENERATED by scripts/build-corpus.ts — do not edit.
export interface CodeSample { path: string; label: string; source: string }
export const CODE_SAMPLES: CodeSample[] = ${JSON.stringify(samples, null, 2)};
`,
  "utf8"
);
console.log(`code samples: ${samples.length} files -> src/data/codesample.generated.ts`);
